### ISSUE TITLE
Lenovo redfish API document

### ISSUE THREAD

**Issue by no-reply-xx** [lenovo/python-redfish-lenovo#101]
This repo is very useful when I setup Lenovo servers, do you have Lenovo redfish API document link? I can use for more research.

**Comment by renxulei** [comment]
@no-reply-xx Hi, please check if the link below can help you, thanks!
https://sysmgt.lenovofiles.com/help/topic/com.lenovo.systems.management.xcc.restapi.doc/xcc_restapi_book.pdf
