### ISSUE TITLE
firmware upgrades on all models and versions

### ISSUE THREAD

**Issue by shaikk-arch** [lenovo/python-redfish-lenovo#103]
Hi @renxulei 

How are you ?

I have Lenovo servers which needs firmware upgrades for model SR630/SD530 using python script on multiple servers.
I am looking for a better way which upgrades, Using commands or utility which supports all type of versions.
Can you please suggest which one is the better way to upgrade both BIOS and iLO firmware 

Thanks,
Shaik

**Comment by renxulei** [comment]
@shaikk-arch Sorry for late response. 
For Lenovo servers,  Lenovo provided console software like LXCA (Lenovo XClarity Administartor) for multiple servers' firmware upgrades. If you want to use open source tool, maybe Ansible can help you. Ansible is python-based tool, have Redish module to provide SimpleUpdate command to do firmware update via pull way, and Ansible also have the capability to operate multiple servers. Another way is writing Ansible playbook by using update_firmware.py on this repo. 

For iLO firmware update, I am not sure if Ansible redfish module can work well on it, maybe you can try it or seek the help from iLO's vendor HPE.  Hope these info can help you.

**Comment by shaikk-arch** [comment]
Sure, Thank you so much👍
