### ISSUE TITLE
SNMP settings

### ISSUE THREAD

**Issue by tete2soja** [lenovo/python-redfish-lenovo#184]
Hello,

I don't see any scripts or way to set SNMP settings through Redfish. Any one already work on it?

Thank in advance

ps: I found a command with SSH (`snmp -t on -t1 on -a3 on -l A -cn A`) but it doesn't allow to activate trap categories (Critical, Warning and System).

**Comment by renxulei** [comment]
@tete2soja Sorry, we have no scripts to set SNMP trap currently, we plan to add it. Could you let me know your server's model name? Such as "ThinkSystem SR650", so that I can validate the scripts on the server you are using as first priority.

**Comment by tete2soja** [comment]
Thanks for the really quick reply. I have currently one SR630 and one SR650 on my side.

**Comment by renxulei** [comment]
@tete2soja We have published 2 scripts to get/set SNMP setting, lenovo_set_snmp_global.py and lenovo_get_snmp_global.py, please take a look if they can help you, thanks.

**Comment by tete2soja** [comment]
Hello,

Perfect! They do perfectly the job I wanted!

Thanks for the quick replies 👍
