### ISSUE TITLE
Change hostname

### ISSUE THREAD

**Issue by tete2soja** [lenovo/python-redfish-lenovo#191]
Hello,

I have another question regarding hostname (`System Name` and `Ethernet Host Name`).

I can get the information with the script `get_bmc_inventory.py`but don't find how to setup this value. I tried to use `set_bios_attribute.py` script with `--name FQDN --value TEST` as arguments but got this reply:

`This bios attribute 'FQDN' not supported on this platform`.

This operation can be done with this script using another name? With another script?

Thanks in advance for your time and reply.

**Comment by renxulei** [comment]
@tete2soja We have no dedicated script to set HostName currently, but you can use our raw_command_patch.py to change HostName as below:

_# python raw_command_patch.py -i 10.10.10.10 -u USERID-p PASSW0RD --resource_uri "/redfish/v1/Managers/1/EthernetInterfaces/NIC" --body "{\"HostName\": \"myhostname\"}_

Please let me know if it can help you, thanks!

**Comment by tete2soja** [comment]
Hello,

Perfectly work! Thanks. Do you know the URI path to change the `System Name` as well?

Have a nice day!

**Comment by renxulei** [comment]
@tete2soja Sorry for late response. You can change "System Name" by setting the property "Location/PostalAddress/Name" under /redfish/v1/Chassis/1 as below, hope it is what you want.
_# python raw_command_patch.py -i 10.10.10.10 -u USERID -p PASSW0RD --resource_uri "/redfish/v1/Chassis/1" --body "{\"Location\":{\"PostalAddress\":{\"Name\":\"mysysname\"}}}"_
