### ISSUE TITLE
How to build a raid volume ?

### ISSUE THREAD

**Issue by mdaguete** [lenovo/python-redfish-lenovo#2]
Hi,

How can I build a raid volume with redfish commands ?

Thanks.

**Comment by renxulei** [comment]
Hi, Mdaguete, thanks for your question.  
About your question, Currently there is no redfish commands to support building raid volumes. I am tracking if there is solid plan to provide this capability in future, I will give you update once I got the results.

If you just want to implement building raid volume via network, lenovo provided other ways to support this, like via lenovo BMC's WebGui or command line tool. if you need further help about this, feel free to let me know.

Thanks.

**Comment by renxulei** [comment]
New firmware supported RAID configuration via Redfish, and added new scripts to support RAID configuration, so close this.
lenovo_create_raid_volume.py
lenovo_delete_raid_volume.py

**Comment by mastier** [comment]
Hi @renxulei So far I see the  request does not send speicific physical disk
For me it fails with code 500
I got 2x SSD 1TB and 8x8TB HDD on one conttroller and wants to create RAID1

Does the firmware support passing the actual drives ? So I could modify the lenovo-create_raid_volume.py script to pass list of drives in the request body ?
Similarly to iDRAC ? like https://jonamiki.com/2019/04/14/example-redfish-rest-calls-create-raid-volume/
Or it will work only when the list of drives matches the RAIDType  ?


Also would be cool if the REST API guide was updated accordingly
also would like to know which firmware version supports it ?
I got mine SR650 updated to the newest firmware on all components
https://sysmgt.lenovofiles.com/help/topic/com.lenovo.systems.management.xcc.restapi.doc/xcc_restapi_book.pdf
