### ISSUE TITLE
Complex Password Setting on SR635/SR655

### ISSUE THREAD

**Issue by jlindgreen** [lenovo/python-redfish-lenovo#299]
Hi Team,
Would it be possible to add the ability to disable/enable complex passwords on SR635/SR655 to lenovo_set_bmc_user_global.py ?

**Comment by jixj5** [comment]
Yes, we will add it for SR635/SR655.

**Comment by jixj5** [comment]
Hi, @jlindgreen，we have updated the script `lenovo_set_bmc_user_global.py` to support complex password setting on SR635/SR655.
