### ISSUE TITLE
about how to get XCC service data 

### ISSUE THREAD

**Issue by Hywfred** [lenovo/python-redfish-lenovo#300]
Hi all, we want to download service data from XCC redfish and open lenovo support ticket. At present I have no idea how to download the service data. It seems not so many docs about this online, either. 
So my question is do you have idea how to do that using python-redfish-library? Thank you in advance.

**Comment by jixj5** [comment]
Hi, you can use lenovo_export_ffdc_data.py script to download service data. 
Using `python lenovo_export_ffdc_data.py -h` to get help message.

**Comment by Hywfred** [comment]
> Hi, you can use lenovo_export_ffdc_data.py script to download service data. Using `python lenovo_export_ffdc_data.py -h` to get help message.

Hi jixj5, thank you for your sharing. But I notice that when I download service data from remote board, it is a tzz file, while when I download logs via this API, it is a tgz file. I once met the situation where vendor said they couldn't parse tgz log file and asked to download tzz file. So my question here is that is it ok to use tgz file instead of tzz file to open support ticker to Lenovo? Looking forward to your reply. Thank you again.

**Comment by jixj5** [comment]
Hi, it is tzz file for XCC via redfish API.  Do you mean you want to download tgz file? If yes, What's the server and FW version you use to download service data? Then I can reproduce your environment to test.

**Comment by Hywfred** [comment]
> Hi, it is tzz file for XCC via redfish API. Do you mean you want to download tgz file? If yes, What's the server and FW version you use to download service data? Then I can reproduce your environment to test.

Hi, tzz is exactly what I need. But using redfish api,I can only get tgz file. Could you please double check that redfish could also download tzz service data？If yes then it is really great. and does above example also provide tgz log？ Thank you.

**Comment by Hywfred** [comment]
> that IMM2 server can download tgz file and XCC server can download tzz file. W

Hi, AFAIK IMM2 doesn't support redfish API. I also tried to access the API of IMM2 systems, all end up with failrues.
So right now I'm working on XCC server and yes they could provide tzz log file. But when I use the tzz file to open Lenovo support ticket, they told me they could not parse the log file and asked me to download logs via clicking `service data` button in remote board to get logs. So I mean if we could download tgz log or any type of log that could be parsed by Lenovo support team, that would be great.
Actually we couldn't do nothing about IMM2 server and no progress on getting logs for XCC servers.

**Comment by jixj5** [comment]
Hi, yes, IMM2 doesn't support redfish API. We have not reproduced your issue. Can you provide me your machine serial number, then we can investigate where the problem is.

**Comment by Hywfred** [comment]
> Hi, yes, IMM2 doesn't support redfish API. We have not reproduced your issue. Can you provide me your machine serial number, then we can investigate where the problem is.

Hi, serial number of one of the machines is S4APV779. Our goal is to get tgz log from XCC server or other format log file which could be parsed by Lenovo support team. Currently it can only serve tzz file, which seems not work for maintenance.

**Comment by jixj5** [comment]
Hi, can you upload the tzz file your downloaded via redfish to this url，[https://logupload.lenovo.com/](url). Then we can confirm if it can be parsed, if not, we will try to contact Lenovo support team to reslove.

**Comment by Hywfred** [comment]
> 

Hi sorry that I have to correct myself. Currently what we got from redfish API is tgz file and what we want to get is tzz file. I've uploaded tgz file I got to above file server. Please help to check if that file could be parsed or not. Thank you very much.

**Comment by Hywfred** [comment]
Hi,

Besides I have another question that when we post `ffdc_data_uri`, what's the different between the post data `ServiceDataFile` and `ProcessorDump` in filed `DataCollectionType`?

**Comment by jixj5** [comment]
> 

Hi,it is the key param (`"DataCollectionType":"ServiceDataFile"`)that you get tgz file，if it is `"ProcessorDump"` it will be tzz file.

When the value of DataCollectionType is “ProcessorDump” and the value of “InitializationNeeded” is true, a task will be created to let user know the transfer progress and return a download URI if there is no input parameter “ExportURI” or the parameter value is empty. When DataCollectionType is ServiceDataFile, the FFDC file will directly be sent to the target server and return 200 OK or return a download URI.

**Comment by Hywfred** [comment]
Hi jixj5, 
Thank you for your explanation. That really helps me a lot. Because at first glance, param ServiceDataFile looks more meaningful. So I didnt try the other one. I will give it a try later. Besides,the log could be dumped to the local disk,right?

**Comment by jixj5** [comment]
Yes,it can be dumped to the local disk.

**Comment by Hywfred** [comment]
> Yes,it can be dumped to the local disk.

Hi jixj5, sorry for late reply. 
I've successfully got tzz log file(AKA service data) for xclarity servers. Thank you so much for your help. I think this issue could be closed.
