### ISSUE TITLE
redfish issue with ThinkEdge SE450 and SR650

### ISSUE THREAD

**Issue by mmorency2021** [lenovo/python-redfish-lenovo#308]
we are getting some redfish errors when trying to provision these servers using ZTP ( openshift).
 actually while testing the SE450 on OCP4.12 and ztp 4.12 i found the below error when ztp is trying to power up the server: 
errorMessage: 'Failed to get power state for node 79505ed0-8b1b-43fd-b39d-42291b56200a.
      Error: Redfish exception occurred. Error: Resource https://192.168.26.178/redfish/v1/Systems/1

This is the first time i am seeing this issue. last time it was related to virtual media. 
even the api call below is getting general error access denied.

# curl https://192.168.26.178/redfish/v1/Systems/1 -X GET -k -H "Content-type: application/json" -H "Authorization: Basic VVNFUklEOlJlK"
{"error":{"@Message.ExtendedInfo":[{"MessageSeverity":"Critical","Resolution":"Attempt to ensure that the URI is correct and that the service has the appropriate credentials.","@odata.type":"#Message.v1_1_0.Message","Message":"While attempting to establish a connection to /redfish/v1/Systems/1, the service denied access.","MessageId":"Base.1.8.AccessDenied","MessageArgs":["/redfish/v1/Systems/1"]}],"message":"A general error has occurred. See ExtendedInfo for more information.","code":"Base.1.8.GeneralError"}}

 Note that i am using the user: USERID.

**Comment by renxulei** [comment]
@mmorency2021  Thank you to report this issue. Could you tell us your XCC and UEFI's firmware versions? And if possible, could you help to collect the service data (.tzz file, you can download it from Web GUI of XCC) and upload it to [https://logupload.lenovo.com/](https://logupload.lenovo.com/) so that we can make detailed investigation based on the service data? Thanks.

**Comment by mmorency2021** [comment]
@renxulei , thanks for your reply.
below the requested info:
Type | Status | Version | Build | Release Date
UEFI | Active | 1.01 | CME104I | 2022-03-17



ThinkEdge SE450 | Power On (Booting OS or in undetected OS)
-- | --
Machine Type/Model | 7D8TCTO1WW

Front Panel USB Port Management | Enabled
BMC License | Lenovo XClarity Controller Enterprise Upgrade |  
  
BMC Version | 1.11 (Build ID: USX304Y)

service data files uploaded as well.

thanks

**Comment by renxulei** [comment]
@mmorency2021 thanks for your information and sorry for late response, we were in public holiday past one week.  Team checked redfish related logs, we saw many redfish access logs from the 23th, Jan and it did not report error, so I want to double-confirm with you if the issue still exists, I am afraid that some redfish error info was over-written by new log.  If the issue still exists (curl command still fails), could you re-collect the service data(.tzz) at once after the command failed?  thanks.

**Comment by mmorency2021** [comment]
Hi Xulei Ren,
You can close the ticket. Issue has been resolved.

**Comment by renxulei** [comment]
@mmorency2021 thanks for your response, good to hear the issue is resolved.

**Comment by georgemarin776** [comment]
@mmorency2021 i'm sorry for reopening the discussion, but how did you fix the issue? I'm encountering something similar
