### ISSUE TITLE
LenovoSecurityService.GenerateCertificate

### ISSUE THREAD

**Issue by Tic2k** [lenovo/python-redfish-lenovo#33]
Hi,

i´m trying to get a Self Signed Certificate to the Server via redfish.
 found a request target like this:

https://168.192.0.2/redfish/v1/Managers/1/Oem/Lenovo/Security/Actions/LenovoSecurityService.GenerateCertificate

The Body of the request is:
{
    "CountryName": "DE",
    "Service": "Server",
    "StateOrProvinceName": "State",
    "LocalityName": "Test City",
    "OrganizationName": "Test",
    "HostName": "test_01"
}

but i get allways one error message and dont know what is missing. 

{
    "error": {
        "@Message.ExtendedInfo": [
            {
                "MessageArgs": [
                    "LenovoSecurityService.GenerateCertificate",
                    "CountryName"
                ],
                "Resolution": "Supply the action with the required parameter in the request body when the request is resubmitted.",
                "MessageId": "Base.1.4.ActionParameterMissing",
                "Severity": "Critical",
                "Message": "The action LenovoSecurityService.GenerateCertificate requires the parameter CountryName to be present in the request body.",
                "@odata.type": "#Message.v1_0_6.Message"
            }
        ],
        "code": "Base.1.4.GeneralError",
        "message": "A general error has occurred. See ExtendedInfo for more information."
    }
}

Till now, i didnt find any example in the Internet :(
Maybe u can help here or create an example for this Action?

regards

**Comment by renxulei** [comment]
@Tic2k  thanks for your question.
Please try the body as below:
{
	"RequiredCertificateData": {
	    "CountryName": "DE",
	    "Service": "Server",
	    "StateOrProvinceName": "State",
	    "LocalityName": "Test City",
	    "OrganizationName": "Test",
	    "HostName": "renxulei"
	}
}

if you still have problem, feel free to let me know.

**Comment by Tic2k** [comment]
Thank u,

this works now :)
