### ISSUE TITLE
'Step Level' for get_cpu_inventory.py 

### ISSUE THREAD

**Issue by maryumahmad** [lenovo/python-redfish-lenovo#36]
Please check the possibility of adding 'Step level' in the output of the python script 'get_cpu_inventory.py'

**Comment by renxulei** [comment]
@maryumahmad thanks for your report, the script will add step info support. after the code updated, I will let you know.

**Comment by renxulei** [comment]
@maryumahmad Sorry for late update. Code have been changed to get more property, step info can be shown under ProcessorId property. please confirm if it can meet your needs. thanks!
