### ISSUE TITLE
Delete user account fails on Whitely

### ISSUE THREAD

**Issue by shibingxun** [lenovo/python-redfish-lenovo#55]
On SR650v2, the created user account can't be deleted by the script "lenovo_delete_bmc_user.py"

Failed message as below:
=====================================
neil@DevLab:~/work/redfish/python-redfish-lenovo/examples$ python lenovo_delete_bmc_user.py --username user1
/redfish/v1/AccountService/Accounts/2
{'If-Match': u'"c34e325042a1436b4098bd97b278fb7e"'}
Url '412
content-language en
transfer-encoding chunked
strict-transport-security max-age=31536000; includeSubDomains
server XCC Web Server
connection keep-alive
cache-control no-store
date Wed, 19 Feb 2020 09:19:52 GMT
odata-version 4.0
content-type application/json

{"error":{"@Message.ExtendedInfo":[{"MessageArgs":[],"Resolution":"Please correct precondition fields in request header.","MessageId":"ExtendedError.1.1.EtagPreconditionalFailed","Severity":"Warning","Message":"One or more conditions given in the request header fields is evaluated to false when tested on the server.","@odata.type":"#Message.v1_0_8.Message"}],"code":"Base.1.6.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information."}}
' response Error code 412
error_message: One or more conditions given in the request header fields is evaluated to false when tested on the server.neil@DevLab:~/work/redfish/python-redfish-lenovo/examples$

**Comment by renxulei** [comment]
@shibingxun the script has been fixed, please confirm it, thanks!

**Comment by shibingxun** [comment]
Fixed
